### ISSUE TITLE
How to run randomizer?

### ISSUE THREAD

**Issue by FrostyFreeze** [cTooshi/stardew-valley-randomizer#4]
I installed SMAPI and the randomizer, unzipped it into the /mods folder and it doesn't seem to run when I open up Stardew. Am I missing something?
![image](https://user-images.githubusercontent.com/24865253/49621955-97fa3280-f995-11e8-8378-0c8cfe290efd.png)
![image](https://user-images.githubusercontent.com/24865253/49621972-a6484e80-f995-11e8-8613-fc21dace412e.png)

Figured including a picture of the folders might help.
Thanks!

**Comment by cTooshi** [comment]
yeah you need to download from curseforge, ill put up the zip file on github soon though.
