### ISSUE TITLE
Manifest has invalid name.

### ISSUE THREAD

**Issue by Rurikar22** [cTooshi/stardew-valley-randomizer#5]
![image](https://user-images.githubusercontent.com/14209382/50576779-3dfb5a00-0de7-11e9-9ee0-ad7047b0b768.png)

Followed the instructions and got stuck here. I tried messing with the file names, but I don't really know stardew modding. Any ideas?

**Comment by RossWorkman** [comment]
Hey Rawb. I had this same issue too with the github download. If you use the curse forge link, then it should work with no hassle. 
https://stardewvalley.curseforge.com/projects/stardew-valley-randomizer

Wondering if we'll be seeing this on Rawb TV, if so, I look forwards to it! If not, I hope you enjoy regardless.
